import type { Station, FilterOption } from "./types"

export const filterOptions: FilterOption[] = [
  { id: "fast", label: "Fast 150kW+", category: "power" },
  { id: "ultrafast", label: "Ultra 250kW+", category: "power" },
  { id: "nacs", label: "NACS", category: "connector" },
  { id: "ccs", label: "CCS", category: "connector" },
  { id: "chademo", label: "CHAdeMO", category: "connector" },
  { id: "starbucks", label: "Starbucks", category: "brand" },
  { id: "target", label: "Target", category: "brand" },
  { id: "restrooms", label: "Restrooms", category: "amenity" },
  { id: "available", label: "Available Now", category: "availability" },
]

export const stations: Station[] = [
  {
    id: "mock-1",
    externalId: "nrel-64274",
    name: "Electrify America — Vacaville Premium Outlets",
    address: "321 Nut Tree Rd",
    city: "Vacaville",
    state: "CA",
    zip: "95687",
    lat: 38.357,
    lng: -121.978,
    network: "Electrify America",
    connectorTypes: ["CCS", "CHAdeMO"],
    maxPowerKw: 350,
    stalls: [
      { id: "s1", stallNumber: 1, powerKw: 350, connector: "CCS", status: "available" },
      { id: "s2", stallNumber: 2, powerKw: 350, connector: "CCS", status: "occupied" },
      { id: "s3", stallNumber: 3, powerKw: 150, connector: "CHAdeMO", status: "available" },
      { id: "s4", stallNumber: 4, powerKw: 150, connector: "CCS", status: "broken" },
    ],
    pricePerKwh: 0.48,
    ccScore: 8.6,
    chargeScore: {
      overall: 4.2,
      uptimeHistory: 4.5,
      realTimeAvailability: 4.0,
      communityVerification: 4.2,
      networkBenchmark: 4.0,
    },
    brewScore: {
      overall: 4.4,
      foodOptions: 4.8,
      restroomAccess: 5.0,
      retailQuality: 4.5,
      venueQuality: 4.2,
      environment: 4.0,
      hoursCoverage: 4.5,
    },
    reliability: "high",
    lastVerified: "12 min ago",
    lastVerifiedAt: Date.now() - 12 * 60 * 1000,
    photoCount: 24,
    distanceMiles: 22.4,
    detourMiles: 0,
    amenities: [
      { id: "a1", name: "Starbucks", brand: "Starbucks", category: "coffee", walkMinutes: 3, distanceMeters: 180, rating: 4.2, hours: "5:30am–9pm", lat: 38.358, lng: -121.979 },
      { id: "a2", name: "McDonald's", brand: "McDonald's", category: "food", walkMinutes: 2, distanceMeters: 120, rating: 3.8, hours: "6am–11pm", lat: 38.356, lng: -121.977 },
      { id: "a3", name: "Restrooms (mall)", brand: "", category: "restroom", walkMinutes: 1, distanceMeters: 60, rating: 0, hours: "10am–9pm", lat: 38.357, lng: -121.978 },
    ],
    fallbackStationId: "mock-2",
  },
  {
    id: "mock-2",
    externalId: "nrel-55102",
    name: "ChargePoint — Davis Safeway",
    address: "1451 W Covell Blvd",
    city: "Davis",
    state: "CA",
    zip: "95616",
    lat: 38.558,
    lng: -121.762,
    network: "ChargePoint",
    connectorTypes: ["CCS", "J1772"],
    maxPowerKw: 62,
    stalls: [
      { id: "s5", stallNumber: 1, powerKw: 62, connector: "CCS", status: "available" },
      { id: "s6", stallNumber: 2, powerKw: 62, connector: "J1772", status: "available" },
    ],
    pricePerKwh: 0.29,
    ccScore: 7.1,
    chargeScore: {
      overall: 3.6,
      uptimeHistory: 3.8,
      realTimeAvailability: 3.5,
      communityVerification: 3.2,
      networkBenchmark: 3.8,
    },
    brewScore: {
      overall: 3.5,
      foodOptions: 4.0,
      restroomAccess: 4.0,
      retailQuality: 3.5,
      venueQuality: 3.2,
      environment: 3.0,
      hoursCoverage: 3.5,
    },
    reliability: "medium",
    lastVerified: "3 hours ago",
    lastVerifiedAt: Date.now() - 3 * 60 * 60 * 1000,
    photoCount: 6,
    distanceMiles: 14.2,
    detourMiles: 2.1,
    amenities: [
      { id: "a4", name: "Safeway", brand: "Safeway", category: "grocery", walkMinutes: 1, distanceMeters: 40, rating: 3.9, hours: "5am–1am", lat: 38.559, lng: -121.762 },
    ],
    fallbackStationId: null,
  },
]
